stages:
  - test

before_script:
  - echo "INSTALLING DEPENDENCIES:" 
  - pip install poetry
  - poetry install

test-job:
  stage: test
  script:
    - echo "TESTING CODE:"
    - poetry run pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml

pages:
  script:
    - echo "DOCUMENTATION"
    - poetry run pdoc src --html -o public
  needs: []
  artifacts:
    paths:
      - public