defaults:
  - process: turbofan
  - model: model
  - _self_

raw:
  dir: data/raw/
  name: train_FD001.txt
  path: ${raw.dir}/${raw.name}

processed:
  dir: data/processed/
  name: input_processed.feather
  path: ${processed.dir}/${processed.name}

final:
  dir: data/final/
  name: results.feather
  path: ${final.dir}/${final.name}

models:
  dir: models/
  name: models.pickle
  path: ${models.dir}/${models.name}