defaults:
  - process: turbofan
  - model: model
  - _self_

raw:
  dir: data/raw
  name: train_FD001.txt
  path: ${raw.dir}/${raw.name}

processed:
  dir: data/processed/
  name: input_processed.feather
  path: ${processed.dir}/${processed.name}

result:
  dir: data/final
  name: results.feather
  path: ${result.dir}/${result.name}

prediction:
  dir: data/final
  name: prediction.feather
  path: ${result.dir}/${model_prediction.name}


models:
  dir: models
  name: models.pickle
  path: ${models.dir}/${models.name}