target_feature: "sensor_4" # can be deleted, but then also test needs to be adapted
cat_features:
  - 'unit_number'
  - 'cycles'
  - 'operational_setting_1'
  - 'operational_setting_2'
  - 'operational_setting_3'